### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kyyberi** [apinf/swagger-parser#19]
We need roadmap for this.

**Comment by mauriciovieira** [comment]
Related https://github.com/apinf/apinf-bot/issues/17

**Comment by mauriciovieira** [comment]
@kyyberi to ease organization and planning, I think we should either

- Kill/delete https://github.com/apinf/apinf-bot/ project after migrating its feature issues to [this repository](https://github.com/apinf/apibot.ai/). Host Roadmap documentation on [this repository](https://github.com/apinf/apibot.ai/).
or
- Host Roadmap on https://github.com/apinf/apinf-bot/ and remove all other issues from there, after migration to [this repository](https://github.com/apinf/apibot.ai/).

What do you think it is most appropriate?

**Comment by mauriciovieira** [comment]
OK, according to conversation on our chat, closing this comment in favor of https://github.com/apinf/apinf-bot/issues/17

**Comment by mauriciovieira** [comment]
Reopening. We decided to kill https://github.com/apinf/apinf-bot/

**Comment by mauriciovieira** [comment]
https://github.com/apinf/apibot-roadmap/issues/17 will handle the purpose of this task
